steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds', 'submit', '.',
      '--tag', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME,
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--port', '3000',
      '--platform', 'managed',
      '--region', 'us-central1',
    ]

timeout: '600s'
