#pack build --builder=gcr.io/buildpacks/builder IMAGE_NAME
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']  # Install dependencies

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']  # Run tests

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # Build your application
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--port'
      - '3000'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

timeout: '600s'
