steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Uncomment the following block if you want to build a Docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'build'
  #     - '--tag=gcr.io/$PROJECT_ID/$_SERVICE_NAME'
  #     - '.'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_SERVICE_NAME', '--source', '.', '--region', 'us-central1', '--port', '3000', '--platform', 'managed']
    # Uncomment the following line if you want to deploy using a pre-built Docker image
    # args: ['run', 'deploy', '$_SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '--region', 'us-central1', '--platform', 'managed']

substitutions:
  _SERVICE_NAME: my-nuxt-service
