#pack build --builder=gcr.io/buildpacks/builder IMAGE_NAME
steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: pack
    args:
      - 'build'
      - '$_SERVICE_NAME'
      - '--builder gcr.io/buildpacks/builder:latest'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--port'
      - '3000'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

timeout: '600s'
